### ISSUE TITLE
crypto crash

### ISSUE THREAD

**Issue by hauseja3** [Ceskasporitelna/cs-core-sdk-droid#10]
GGo PROD Android 1.12.3
Happens only on Android 6 and 7 devices
170 Crashes from Locker
Logs 1:
Version Code: 26
Version Name: 1.12.3
Android: 7.0
Manufacturer: HUAWEI
Model: PRA-LX1
Date: Wed Jul 12 12:53:39 GMT+02:00 2017
cz.csas.cscore.error.CsCoreError: Crypto operation failed. See underlying error.
at cz.csas.cscore.client.crypto.CryptoManagerImpl.encryptPBKDF2(CryptoManagerImpl.java:123)
at cz.csas.cscore.storage.KeychainManagerImpl.storeOfflinePasswordHash(KeychainManagerImpl.java:209)
at cz.csas.cscore.locker.LockerImpl$7.run(LockerImpl.java:456)
at android.os.Handler.handleCallback(Handler.java:755)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:156)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.security.spec.InvalidKeySpecException: Could not generate secret key
at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:474)
at cz.csas.cscore.client.crypto.CryptoManagerImpl.encryptPBKDF2(CryptoManagerImpl.java:121)
... 6 more
Caused by: java.lang.IllegalArgumentException: password empty
at com.android.org.bouncycastle.jcajce.provider.digest.SHA1$BasePBKDF2WithHmacSHA1.engineGenerateSecret(SHA1.java:135)
at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:463)
... 7 more
Logs 2:
Version Code: 26
Version Name: 1.12.3
Android: 6.0.1
Manufacturer: samsung
Model: SM-A520F
Date: Tue Jul 18 10:41:41 GMT+02:00 2017
java.lang.IllegalArgumentException: password empty
at com.android.org.bouncycastle.jcajce.provider.digest.SHA1$BasePBKDF2WithHmacSHA1.engineGenerateSecret(SHA1.java:135)
at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:187)
at cz.csas.cscore.client.crypto.CryptoManagerImpl.encryptPBKDF2(CryptoManagerImpl.java:121)
at cz.csas.cscore.storage.KeychainManagerImpl.storeOfflinePasswordHash(KeychainManagerImpl.java:209)
at cz.csas.cscore.locker.LockerImpl$7.run(LockerImpl.java:456)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by hauseja3** [comment]
TODO:
Enrich offline verification description in documentation.
